### ISSUE TITLE
import com.bizdata.url.UrlUtil;

### ISSUE THREAD

**Issue by shushengming** [sdevil507/micro-service-framework#1]
<dependency>
				<groupId>com.bizdata</groupId>
				<artifactId>common-utils</artifactId>
				<version>1.0.1</version>
			</dependency>

这个估计是个内部maven项目里的jar包。缺失了这个包，目前项目启动不了。希望能够补充

**Comment by sdevil507** [comment]
@shushengming 是的,原先私服已经停了。我已经把公用包合并进来！
#4b4bb966d28cfba0a0d0c1500bbe5f272c6fea94

**Comment by sdevil507** [comment]
@shushengming 是的，私服已经停用了。我已经把相关包合并进项目了。
